### PR TITLE
upgrade to postcss 7

### PR DESCRIPTION
**Pull request by schelmo**
remove package-lock.json and move it to .gitignore

### CODE REVIEW

**Comment by seaneking** [comment]
`package-lock.json` should not be ignored, it's whole purpose is to ensure that dependencies stay consistent to avoid runtime regressions. 

That said just realised that this repo uses both `yarn.lock` and the npm lockfile. Feel free to remove/continue ignoring the yarn one.

Rest LGTM 👍

**Comment by schelmo** [comment]
i would remove both. see:
https://stackoverflow.com/a/44210813

**Comment by schelmo** [comment]
hmm the the job with node 8 fails with npm (previously used yarn)

**Comment by schelmo** [comment]
hmm lets keep it like before, upgrade to postcss 7 and i will make a pr to discuss the removal these two files

**Comment by seaneking** [comment]
> i would remove both. see: stackoverflow.com/a/44210813

The stackoverflow you linked to explains exactly why you _should_ commit the `package-lock.json` to source control. I won't be accepting a PR to remove it.

**Comment by schelmo** [comment]
okey i removed the yarn.lock but the test on node 6 fails in ci because of mocha 6.1.0 version
will push again if mocha 6.1.1 available for npm

**Comment by schelmo** [comment]
do this needs something else?

**Comment by ai** [comment]
@seaneking how can I help here (if we need something else to fix?)

**Comment by seaneking** [comment]
Looks good now, I'll merge it

**Pull request merged**
